[debug] Created tunnel using local port: '40403'

[debug] SERVER: "127.0.0.1:40403"

[debug] Original chart version: ""
[debug] CHART PATH: /home/bsscoe/song/helm/chart/prometheus-redis-exporter

NAME:   prometheus-redis-exporter
REVISION: 1
RELEASED: Wed Mar 27 17:48:47 2019
CHART: prometheus-redis-exporter-1.0.2
USER-SUPPLIED VALUES:
{}

COMPUTED VALUES:
annotations: {}
env: {}
extraArgs: {}
image:
  pullPolicy: IfNotPresent
  repository: oliver006/redis_exporter
  tag: v0.28.0
rbac:
  create: true
  pspEnabled: true
redisAddress: redis://myredis:6379
replicaCount: 1
resources: {}
service:
  annotations: {}
  port: 9121
  type: ClusterIP
serviceAccount:
  create: true
  name: null

HOOKS:
MANIFEST:

---
# Source: prometheus-redis-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-redis-exporter
  labels:
    app: prometheus-redis-exporter
    chart: prometheus-redis-exporter-1.0.2
    release: "prometheus-redis-exporter"
    heritage: "Tiller"
---
# Source: prometheus-redis-exporter/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: prometheus-redis-exporter
  labels:
    app: prometheus-redis-exporter
    chart: prometheus-redis-exporter-1.0.2
    heritage: Tiller
    release: prometheus-redis-exporter
rules:
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [prometheus-redis-exporter]
---
# Source: prometheus-redis-exporter/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: prometheus-redis-exporter
  labels:
    app: prometheus-redis-exporter
    chart: prometheus-redis-exporter-1.0.2
    heritage: Tiller
    release: prometheus-redis-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-redis-exporter
subjects:
- kind: ServiceAccount
  name: prometheus-redis-exporter
---
# Source: prometheus-redis-exporter/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prometheus-redis-exporter
  labels:
    app: prometheus-redis-exporter
    chart: prometheus-redis-exporter-1.0.2
    release: prometheus-redis-exporter
    heritage: Tiller
  annotations:
    {}
spec:
  type: ClusterIP
  ports:
    - name: redis-exporter
      port: 9121
      targetPort: exporter-port
      protocol: TCP
  selector:
    app: prometheus-redis-exporter
    release: prometheus-redis-exporter
---
# Source: prometheus-redis-exporter/templates/deployment.yaml
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: prometheus-redis-exporter
  labels:
    app: prometheus-redis-exporter
    chart: prometheus-redis-exporter-1.0.2
    release: prometheus-redis-exporter
    heritage: Tiller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-redis-exporter
      release: prometheus-redis-exporter
  template:
    metadata:
      annotations:
        {}
      labels:
        app: prometheus-redis-exporter
        release: prometheus-redis-exporter
    spec:
      serviceAccountName: prometheus-redis-exporter
      containers:
        - name: prometheus-redis-exporter
          image: "oliver006/redis_exporter:v0.28.0"
          imagePullPolicy: IfNotPresent
          args:
          ports:
            - name: exporter-port
              containerPort: 9121
          env:
            - name: REDIS_ADDR
              value: redis://myredis:6379
          livenessProbe:
            httpGet:
              path: /
              port: exporter-port
          readinessProbe:
            httpGet:
              path: /
              port: exporter-port
          resources:
            {}
---
# Source: prometheus-redis-exporter/templates/podsecuritypolicy.yaml
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: prometheus-redis-exporter
  labels:
    app: prometheus-redis-exporter
    chart: prometheus-redis-exporter-1.0.2
    heritage: Tiller
    release: prometheus-redis-exporter
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName:  'runtime/default'
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  readOnlyRootFilesystem: false
