#FROM ktis-bastion01.container.ipc.kt.com:5000/admin/openjdk:8-jre-alpine
#FROM ktis-bastion01.container.ipc.kt.com:5000/admin/alpine-jre8-millet:1.0
FROM ktis-bastion01.container.ipc.kt.com:5000/admin/openjdk-millet:8-jdk-alpine

LABEL owner=mmp-project-team
ENV TZ Asia/Seoul
COPY target/RestApi-0.0.1-SNAPSHOT.jar app.jar
CMD ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
