kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-elasticsearch-client
  namespace: dev-song
rules:
- apiGroups: ["", "batch", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rbd-elasticsearch
  namespace: dev-song
roleRef:
  kind: Role
  name: role-elasticsearch-client
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: elasticsearch-client
  namespace: dev-song
