apiVersion: apps/v1
kind: Deployment
metadata:
  name: flex-file-api
  labels:
    app: flex-file-api
    version: 1.0.0
    release: flex
spec:
  selector:
    matchLabels:
      app: flex-file-api
      version: 1.0.0
      release: flex
  replicas: 1
  template:
    metadata:
      labels:
        app: flex-file-api
        version: 1.0.0
        release: flex
#      annotations:
#        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: flex-file-api 
        image: 172.16.51.166:5000/flex/flex-file-api:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8091
        envFrom:
        - configMapRef:
            name: flex-file-api
        volumeMounts:
        - mountPath: /etc/localtime
          name: timezone-config
        - mountPath: /data/flex/uploads
          name: file-uploads
        securityContext:
          privileged: true
#        livenessProbe:
#          httpGet:
#            path: /api/be/auth/actuator/health
#            port: 8080
#          initialDelaySeconds: 30
#          periodSeconds: 10
#        readinessProbe:
#          httpGet:
#            path: /api/be/auth/actuator/health
#            port: 8080
#          initialDelaySeconds: 30
#          periodSeconds: 10
#        resources:
#          requests:
#            cpu: "500m"
#            memory: "1250Mi"
#          limits:
#            cpu: "2000m"
#            memory: "1250Mi"
#      nodeSelector:
#        ktis-node: "true"
      nodeName: hsnc-archserver3
      volumes:
      - hostPath:
          path: /usr/share/zoneinfo/Asia/Seoul
        name: timezone-config
      - hostPath:
          path: /data/flex/uploads
        name: file-uploads
