apiVersion: v1
kind: Service
metadata:
  name: flex-file-api
  labels:
    app: flex-file-api
    version: 1.0.0
    release: flex
spec:
  type: ClusterIP
  ports:
  - name: flex-file-api  
    port: 80
    targetPort: 8091
    protocol: TCP
#    nodePort: 30001
#  sessionAffinity: ClientIP
#  sessionAffinityConfig:
#    clientIP:
#      timeoutSeconds: 3600 # default 10800으로 3시간
#  externalTrafficPolicy: Local
  selector:
    app: flex-file-api
    version: 1.0.0
    release: flex
