kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mmp-role-authorize-hostpath
rules:
- apiGroups: ['policy']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames: 
  - example
