
server:
  port: 8080
  servlet:
    context-path: /svc1

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWD:postgres}
    hikari:
      connection-test-query: select 1
      connection-timeout: 5000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
services:
  comment: "컨테이너 클러스터 내외부 서비스 host정보 정의"
  host:
    svc1: ${SVC1HOST:localhost}
    svc2: ${SVC2HOST:localhost}

debug: false