apiVersion: v1
kind: Service
metadata:
  name: flex-oauth2-authorization
  labels:
    app: flex-oauth2-authorization
    version: 1.0.0
    release: flex
spec:
  type: ClusterIP
  ports:
  - name: flex-oauth2-authorization  
    port: 80
    targetPort: 8081
    protocol: TCP
#    nodePort: 30001
#  sessionAffinity: ClientIP
#  sessionAffinityConfig:
#    clientIP:
#      timeoutSeconds: 3600 # default 10800으로 3시간
#  externalTrafficPolicy: Local
  selector:
    app: flex-oauth2-authorization
    version: 1.0.0
    release: flex
