apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: route-micro-svc-2
  labels:
    appName: herasoo
    svcName: micro-svc-2
    version: v1
spec:
  host: sample1-millet.container.ipc.kt.com
  port:
    #targetPort: 80 # service port name!!!
    targetPort: http
  path: "/svc2"
  to:
    kind: Service
    name: service-micro-svc-2 #.herasoo.svc.cluster.local # FQDN is not working!!!
    weight: 100
  wildcardPolicy: None
