apiVersion: v1
kind: Service
metadata:
  name: service-micro-svc-2
  labels:
    appName: herasoo
    svcName: micro-svc-2
    version: v1
spec:
  #type: NodePort
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8090
  selector:
    appName: herasoo
    svcName: micro-svc-2
